# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_jump', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ship_model', models.CharField(max_length=50)),
                ('ship_name', models.CharField(blank=True, default='', max_length=255)),
                ('ship_jump', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registration_number', models.PositiveIntegerField()),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='expeditions.Expedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('system', models.CharField(default='', max_length=255)),
                ('planet', models.CharField(default='', max_length=5)),
                ('number', models.IntegerField()),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='expeditions.Expedition')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='waypoint',
            unique_together=set([('number', 'expedition')]),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('registration_number', 'expedition'), ('user', 'expedition')]),
        ),
    ]
