# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_auto_20161024_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expedition',
            name='teaser_image',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='expedition',
            name='teaser_is_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='gravity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waypoint',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waypoint',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waypoint',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
