# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0004_auto_20161104_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
