# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0005_waypoint_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
