# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0006_expedition_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='teaser_image',
            new_name='teaser_image_url',
        ),
    ]
