# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0007_auto_20161108_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='retracted',
            field=models.BooleanField(default=False),
        ),
    ]
