# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('min_jump', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('system', models.CharField(default='', max_length=255)),
                ('planet', models.CharField(default='', max_length=5)),
                ('number', models.IntegerField()),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expeditions.Expedition')),
            ],
        ),
    ]
