# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(max_length=3)),
                ('pc', models.BooleanField(default=True)),
                ('ship_model', models.CharField(max_length=50)),
                ('ship_name', models.CharField(blank=True, default='', max_length=255)),
                ('ship_jump', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registration_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='waypoint',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='expedition',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='expeditions.Expedition'),
        ),
        migrations.AlterUniqueTogether(
            name='waypoint',
            unique_together=set([('number', 'expedition')]),
        ),
        migrations.AddField(
            model_name='registration',
            name='expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='expeditions.Expedition'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('registration_number', 'expedition'), ('email', 'expedition')]),
        ),
    ]
